### ISSUE TITLE
Support for async context generator

### ISSUE THREAD

**Issue by gaby** [pomponchik/escaping#14]
Hello @pomponchik 

Was looking at the docs, but didnt see support for Async Context Generator, is that supported? If not, could support be added?

Thanks!

Example:

```python
async with escape():
    await func()
```

**Comment by pomponchik** [comment]
Hello!

The `async with` construct is necessary to asynchronously wait for context creation. However, this is not required in this library, since there is no waits, creating a context here is a very easy instant operation.

Therefore, you can use the usual "with" in your asynchronous code without any problems.

**Comment by gaby** [comment]
@pomponchik Makes sense, thank you! Awesome library 💪
